@startuml

skinparam componentStyle uml2

package "'Animal' Aggregate" <<Rectangle>> {
	class Animal <<(A,#fffab8) Aggregate Root>> {
		String nome_animal
		String idade_animal
		String especie
		String raca
		String porte
		List<String> tags_personalidade
		Boolean foi_adotado
		IdAnimal id_animal
		IdAbrigo id_abrigo
		IdPessoa[0..1] id_adotante
		SaudeAnimal[0..1] saude_animal
	}
	class IdAnimal <<(V,DarkSeaGreen) Value Object>> {
		int id_animal
	}
	class SaudeAnimal <<(V,DarkSeaGreen) Value Object>> {
		boolean vacina_raiva
		boolean vermifugado
		boolean castrado
	}
}
Animal "1" --> "0..1" SaudeAnimal : saude_animal
Animal --> IdAnimal : id_animal


@enduml
